version: "3"
networks:
  mynetwork:
services:
  web:
    image: docker-node-mongo
    build: .
    ports:
      - "80:80"
    depends_on:
      - "patients"
      - "db"
    networks:
      - mynetwork
    restart: on-failure
  patients:
    build:
      context: patients
      dockerfile: Dockerfile
    networks:
      - mynetwork
  db:
    image: "mongo"
    ports:
      - "27017:27017"
    networks:
      - mynetwork
